version: '3.3'

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: exchange
      POSTGRES_USER: exchange
      POSTGRES_PASSWORD: 123456
    # command: postgres -c 'log_statement=all'
    ports:
      - 5432:5432
